name: "Build and deploy package"

on:
  push:
    branches:
      - main

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m pip install --upgrade build
          python3 -m build
      - run: |
          python3 -m pip install --upgrade twine
          python3 -m twine upload --verbose -r pypi dist/*
